"""inventário de TI: equipamentos e histórico de movimentações

Revision ID: 246567826a93
Revises: c4e8a2d17f55
Create Date: 2026-09-28 15:03:20.487756
"""
from alembic import op
import sqlalchemy as sa


revision = '246567826a93'
down_revision = 'c4e8a2d17f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('processador', sa.String(length=100), nullable=True),
    sa.Column('memoria', sa.String(length=50), nullable=True),
    sa.Column('armazenamento', sa.String(length=100), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patrimonio')
    )
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.create_index('ix_equipamentos_setor', ['setor'], unique=False)
        batch_op.create_index('ix_equipamentos_situacao', ['situacao'], unique=False)
        batch_op.create_index('ix_equipamentos_usuario', ['usuario_id'], unique=False)

    op.create_table('movimentos_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('momento', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_equipamento', schema=None) as batch_op:
        batch_op.create_index('ix_movimentos_equipamento', ['equipamento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentos_equipamento', schema=None) as batch_op:
        batch_op.drop_index('ix_movimentos_equipamento')

    op.drop_table('movimentos_equipamento')
    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.drop_index('ix_equipamentos_usuario')
        batch_op.drop_index('ix_equipamentos_situacao')
        batch_op.drop_index('ix_equipamentos_setor')

    op.drop_table('equipamentos')
    # ### end Alembic commands ###
