"""estrutura inicial

Revision ID: ef9138d44dc3
Revises: 
Create Date: 2026-09-28 07:29:08.546541
"""
from alembic import op
import sqlalchemy as sa


revision = 'ef9138d44dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=120), nullable=False),
    sa.Column('momento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.create_index('ix_tentativas_chave_momento', ['chave', 'momento'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('setor', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prioridade', sa.String(length=10), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('aberto_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('avaliacao', sa.String(length=10), nullable=True),
    sa.Column('avaliado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_index('ix_chamados_aberto_em', ['aberto_em'], unique=False)
        batch_op.create_index('ix_chamados_responsavel', ['responsavel_id'], unique=False)
        batch_op.create_index('ix_chamados_solicitante', ['solicitante_id'], unique=False)
        batch_op.create_index('ix_chamados_status', ['status'], unique=False)

    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('evento', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index('ix_comentarios_chamado', ['chamado_id'], unique=False)

    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arquivo')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.create_index('ix_anexos_chamado', ['chamado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_index('ix_anexos_chamado')

    op.drop_table('anexos')
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_index('ix_comentarios_chamado')

    op.drop_table('comentarios')
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_index('ix_chamados_status')
        batch_op.drop_index('ix_chamados_solicitante')
        batch_op.drop_index('ix_chamados_responsavel')
        batch_op.drop_index('ix_chamados_aberto_em')

    op.drop_table('chamados')
    op.drop_table('usuarios')
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.drop_index('ix_tentativas_chave_momento')

    op.drop_table('tentativas_login')
    # ### end Alembic commands ###
